package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"unicode"
)

const DefaultConfigPath = "/etc/astra/astracmd.ini"

type AstraConnection struct {
	ID        string
	Name      string
	Login     string
	Password  string
	Interface string
	Port      int
	Debug     bool
}

type GlobalConfig struct {
	ServiceProvider string
}

type Config struct {
	Path        string
	Global      GlobalConfig
	Connections []AstraConnection
}

func (c AstraConnection) Addr() string {
	return fmt.Sprintf("%s:%d", c.Interface, c.Port)
}

func (c AstraConnection) DSN() string {
	return fmt.Sprintf("%s:%s@%s:%d", c.Login, c.Password, c.Interface, c.Port)
}

func (c AstraConnection) DisplayDSN() string {
	return "<" + c.DSN() + ">"
}

func (c AstraConnection) MaskedDSN() string {
	return fmt.Sprintf(
		"%s:%s@%s:%d",
		c.Login,
		maskString(c.Password),
		c.Interface,
		c.Port,
	)
}

func (c AstraConnection) DisplayMaskedDSN() string {
	return "<" + c.MaskedDSN() + ">"
}

func maskString(value string) string {
	return strings.Repeat("*", len([]rune(value)))
}

func LoadConfig(path string) (*Config, error) {
	if err := ensureConfigFile(path); err != nil {
		return nil, err
	}

	cfg, err := readConfig(path)
	if err != nil {
		return nil, err
	}

	cfg.Path = path
	cfg.ensureDefaults()

	return cfg, nil
}

func ensureConfigFile(path string) error {
	if _, err := os.Stat(path); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}

	content := fmt.Sprintf(`# astracmd.ini
#
# astracmd configuration file.

# Default location:
# /etc/astra/astracmd.ini

[GLOBAL]
service_provider = %s

# Connections can be added from the TUI.
# The interface field can contain either an IP address or a domain name.

# Example:
#
# [connection.main]
# name = Main Astra
# login = admin
# password = admin
# interface = 127.0.0.1
# port = 8000
# debug = false
#
# [connection.extra]
# name = Extra Astra
# login = admin
# password = password
# interface = astra.local
# port = 8001
# debug = false
`, writeIniValue("Astra"))

	return os.WriteFile(path, []byte(content), 0644)
}

func readConnections(path string) ([]AstraConnection, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	type iniSection map[string]string

	sections := make(map[string]iniSection)
	order := make([]string, 0)

	currentSection := ""

	scanner := bufio.NewScanner(file)

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		if line == "" {
			continue
		}

		if strings.HasPrefix(line, "#") || strings.HasPrefix(line, ";") {
			continue
		}

		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			currentSection = strings.TrimSpace(line[1 : len(line)-1])

			if strings.HasPrefix(currentSection, "connection.") {
				id := strings.TrimSpace(strings.TrimPrefix(currentSection, "connection."))
				if id != "" {
					if _, ok := sections[id]; !ok {
						sections[id] = make(iniSection)
						order = append(order, id)
					}
				}
			}

			continue
		}

		if !strings.HasPrefix(currentSection, "connection.") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		id := strings.TrimSpace(strings.TrimPrefix(currentSection, "connection."))
		if id == "" {
			continue
		}

		key := strings.ToLower(strings.TrimSpace(parts[0]))
		value := readIniValue(parts[1])

		sections[id][key] = value
	}

	if err := scanner.Err(); err != nil {
		return nil, err
	}

	connections := make([]AstraConnection, 0, len(order))

	for _, id := range order {
		sec := sections[id]

		port, _ := strconv.Atoi(strings.TrimSpace(sec["port"]))
		debug, _ := strconv.ParseBool(strings.TrimSpace(sec["debug"]))

		conn := AstraConnection{
			ID:        id,
			Name:      strings.TrimSpace(sec["name"]),
			Login:     strings.TrimSpace(sec["login"]),
			Password:  strings.TrimSpace(sec["password"]),
			Interface: strings.TrimSpace(sec["interface"]),
			Port:      port,
			Debug:     debug,
		}

		if conn.Name == "" {
			conn.Name = conn.ID
		}

		connections = append(connections, conn)
	}

	return connections, nil
}

func readIniValue(value string) string {
	value = strings.TrimSpace(value)

	if len(value) >= 2 && strings.HasPrefix(value, `"`) && strings.HasSuffix(value, `"`) {
		if unquoted, err := strconv.Unquote(value); err == nil {
			return unquoted
		}
	}

	return value
}

func (cfg *Config) Save() error {
	if err := os.MkdirAll(filepath.Dir(cfg.Path), 0755); err != nil {
		return err
	}

	cfg.ensureDefaults()

	var b strings.Builder

	b.WriteString("# astracmd config.ini\n")
	b.WriteString("# generated by astracmd\n\n")

	b.WriteString("[GLOBAL]\n")
	fmt.Fprintf(&b, "service_provider = %s\n\n", writeIniValue(cfg.ServiceProvider()))

	used := make(map[string]bool)

	for i := range cfg.Connections {
		conn := &cfg.Connections[i]

		conn.ID = sanitizeID(conn.ID)
		if conn.ID == "" || used[conn.ID] {
			conn.ID = cfg.nextIDWithUsed(used)
		}

		used[conn.ID] = true

		fmt.Fprintf(&b, "[connection.%s]\n", conn.ID)
		fmt.Fprintf(&b, "name = %s\n", writeIniValue(conn.Name))
		fmt.Fprintf(&b, "login = %s\n", writeIniValue(conn.Login))
		fmt.Fprintf(&b, "password = %s\n", writeIniValue(conn.Password))
		fmt.Fprintf(&b, "interface = %s\n", writeIniValue(conn.Interface))
		fmt.Fprintf(&b, "port = %d\n", conn.Port)
		fmt.Fprintf(&b, "debug = %t\n\n", conn.Debug)
	}

	return os.WriteFile(cfg.Path, []byte(b.String()), 0644)
}

func writeIniValue(value string) string {
	value = strings.ReplaceAll(value, "\r", " ")
	value = strings.ReplaceAll(value, "\n", " ")
	return strings.TrimSpace(value)
}

func sanitizeID(id string) string {
	id = strings.TrimSpace(id)

	var b strings.Builder

	for _, r := range id {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_' || r == '-' {
			b.WriteRune(r)
		}
	}

	return b.String()
}

func (cfg *Config) NextID() string {
	used := make(map[string]bool)

	for _, conn := range cfg.Connections {
		id := sanitizeID(conn.ID)
		if id != "" {
			used[id] = true
		}
	}

	return cfg.nextIDWithUsed(used)
}

func (cfg *Config) nextIDWithUsed(used map[string]bool) string {
	for i := 1; ; i++ {
		id := fmt.Sprintf("conn%d", i)
		if !used[id] {
			return id
		}
	}
}

func (cfg *Config) UpsertConnection(conn AstraConnection) {
	if conn.ID == "" {
		conn.ID = cfg.NextID()
	}

	for i := range cfg.Connections {
		if cfg.Connections[i].ID == conn.ID {
			cfg.Connections[i] = conn
			return
		}
	}

	cfg.Connections = append(cfg.Connections, conn)
}

func (cfg *Config) DeleteConnection(id string) bool {
	for i := range cfg.Connections {
		if cfg.Connections[i].ID == id {
			cfg.Connections = append(cfg.Connections[:i], cfg.Connections[i+1:]...)
			return true
		}
	}

	return false
}

func readConfig(path string) (*Config, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	type iniSection map[string]string

	global := make(iniSection)
	sections := make(map[string]iniSection)
	order := make([]string, 0)
	currentSection := ""

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}

		if strings.HasPrefix(line, "#") || strings.HasPrefix(line, ";") {
			continue
		}

		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			currentSection = strings.TrimSpace(line[1 : len(line)-1])

			if strings.EqualFold(currentSection, "GLOBAL") {
				continue
			}

			if strings.HasPrefix(currentSection, "connection.") {
				id := strings.TrimSpace(strings.TrimPrefix(currentSection, "connection."))
				if id != "" {
					if _, ok := sections[id]; !ok {
						sections[id] = make(iniSection)
						order = append(order, id)
					}
				}
			}

			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.ToLower(strings.TrimSpace(parts[0]))
		value := readIniValue(parts[1])

		if strings.EqualFold(currentSection, "GLOBAL") {
			global[key] = value
			continue
		}

		if !strings.HasPrefix(currentSection, "connection.") {
			continue
		}

		id := strings.TrimSpace(strings.TrimPrefix(currentSection, "connection."))
		if id == "" {
			continue
		}

		sections[id][key] = value
	}

	if err := scanner.Err(); err != nil {
		return nil, err
	}

	cfg := &Config{
		Global: GlobalConfig{
			ServiceProvider: strings.TrimSpace(global["service_provider"]),
		},
		Connections: make([]AstraConnection, 0, len(order)),
	}

	for _, id := range order {
		sec := sections[id]

		port, _ := strconv.Atoi(strings.TrimSpace(sec["port"]))
		debug, _ := strconv.ParseBool(strings.TrimSpace(sec["debug"]))

		conn := AstraConnection{
			ID:        id,
			Name:      strings.TrimSpace(sec["name"]),
			Login:     strings.TrimSpace(sec["login"]),
			Password:  strings.TrimSpace(sec["password"]),
			Interface: strings.TrimSpace(sec["interface"]),
			Port:      port,
			Debug:     debug,
		}

		if conn.Name == "" {
			conn.Name = conn.ID
		}

		cfg.Connections = append(cfg.Connections, conn)
	}

	cfg.ensureDefaults()

	return cfg, nil
}

func (cfg *Config) ensureDefaults() {
	if strings.TrimSpace(cfg.Global.ServiceProvider) == "" {
		cfg.Global.ServiceProvider = "Astra"
	}
}

func (cfg *Config) ServiceProvider() string {
	if cfg == nil {
		return "Astra"
	}

	value := strings.TrimSpace(cfg.Global.ServiceProvider)
	if value == "" {
		return "Astra"
	}

	return value
}
